name-template: 'v$RESOLVED_VERSION 🎁'
tag-template: 'v$RESOLVED_VERSION'

template: |
  $CHANGES

# Emoji reference: https://gitmoji.carloscuesta.me/
categories:
  - title: 💥 Removed
    label: removed
  - title: ⚠️ Deprecated
    label: deprecated
  - title: 🚀 New Features
    labels:
      - feature
  - title: ✨ Improvements
    labels:
      - enhancement
  - title: 🐛 Bug Fixes
    labels:
      - bug
      - fix
      - bugfix
      - regression
  - title: 📝 Documentation Updates
    label: documentation
  - title: 📦 Dependency Updates
    label: dependencies
  - title: 🔧 Internal Changes
    label: internal
  - title: 🚦 Tests
    labels:
      - test
      - tests

version-resolver:
  major:
    labels:
      - 'removed'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
      - 'deprecated'
      - 'dependencies'
      - 'documentation'
      - 'tests'
      - 'internal'
  patch:
    labels:
      - 'bug'
  default: minor

replacers:
  - search: '/\[*JENKINS-(\d+)\]*\s*-*\s*/g'
    replace: '[JENKINS-$1](https://issues.jenkins.io/browse/JENKINS-$1) - '
