@startuml

component "charts"
component "filters"
component "model"
component "restapi"
component "scm"
component "steps"
component "tokens"
component "util"

charts ..> util
restapi ..> util

@enduml