name: 'GitHub CI'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        jdk: [21, 25]

    runs-on: ${{ matrix.platform }}
    name: on ${{ matrix.platform }} with JDK ${{ matrix.jdk }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5
        with:
          distribution: 'temurin'
          java-version: '${{ matrix.jdk }}'
          check-latest: true
          cache: 'maven'
      - name: Set up Maven
        uses: stCarolas/setup-maven@d6af6abeda15e98926a57b5aa970a96bb37f97d1 # v5
        with:
          maven-version: 3.9.16
      - name: Build with Maven
        env:
          BROWSER: chrome-container
        run: mvn -V --color always -ntp clean verify '-Djenkins.test.timeout=5000' '-Dgpg.skip' -Pno-ui-tests
