name: 'Dependency Check'

on:
  push:
      branches:
      - main
  pull_request_target:

jobs:
  build:
    runs-on: [ubuntu-latest]
    name: Create report

    steps:
      - name: Checkout project
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Set up JDK
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5
        with:
          distribution: 'temurin'
          java-version: 25
          check-latest: true
          cache: 'maven'
      - name: Set up Maven
        uses: stCarolas/setup-maven@d6af6abeda15e98926a57b5aa970a96bb37f97d1 # v5
        with:
          maven-version: 3.9.16
      - name: Cache the NVD database
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: ~/.m2/repository/org/owasp/dependency-check-data
          key: dependency-check
      - name: Build with Maven
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
          OSS_INDEX_TOKEN: ${{ secrets.OSS_INDEX_TOKEN }}
        run: |
          mvn -V --color always -ntp verify -Pci -Powasp
          if [ "${PIPESTATUS[0]}" != "0" ]; then
             exit 1;
          fi
      - name: Upload Dependency Report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: dependency-report
          path: |
            **/target/dependency-check-report.json

