name: 'Quality Monitor » Build'

on:
  push:
      branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: [ubuntu-latest]
    name: Create reports

    steps:
      - name: Checkout project
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Set up JDK
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5
        with:
          distribution: 'temurin'
          java-version: 25
          check-latest: true
          cache: 'maven'
      - name: Set up Maven
        uses: stCarolas/setup-maven@d6af6abeda15e98926a57b5aa970a96bb37f97d1 # v5
        with:
          maven-version: 3.9.16
      - name: Check if quality monitor reports mutation coverage
        run: |
          FILE='.github/quality-monitor.json'
          PATTERN='target/pit-reports/mutations.xml'
          if [ -f "$FILE" ]; then
            if grep -q "$PATTERN" "$FILE"; then
              echo "PIT=-Ppit" >> "$GITHUB_ENV"
            fi
          fi
      - name: Build with Maven
        env:
          PIT: ${{ env.PIT }}
          BROWSER: chrome-container
        run: |
          mvn -V --color always -ntp clean verify $PIT -Pci | tee maven.log
          if [ "${PIPESTATUS[0]}" != "0" ]; then
             exit 1;
          fi
          mv -fv maven.log target/maven.log
      - name: Write PR number
        run: echo '${{ github.event.pull_request.number }}' > pr-number.txt
      - name: Upload Quality Reports
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: quality-reports
          path: |
            pr-number.txt
            **/target/**/*.json
            **/target/**/*.xml
            **/target/**/*.log

