name: 'Sync Labels'
on:
  push:
    branches:
      - master
      - main
    paths:
      - .github/labels.yml
      - .github/workflows/sync-labels.yml

jobs:
  sync-labels:
    name: Sync Labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: brpaz/action-label-syncer@0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels.yml
